language: python
python:
  - "3.6"    
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest queryprocessortest.py
deploy:
  provider: heroku
  api_key:
    secure: gSys3tFLrZWTaI8O1Acq6kURF+CV/wpgpcu2NI4KUBwoVTCOEx9lW7JZI3Dh+onEYxoMkX6kRPJ/Tyi3GRaNaAt84pt6OE2EISlhPdlH/RZuOEUQgDkTa3nVp7R/kj5qY/pCohfdExUJZ9t9nTeP89w3oOYQBlXqCwnzBLhKCWNEDwOjkNypmVBLBFV4yHpEUe0pmAqZA1H1APMEeCoqiJ4BGGQV7QS8BFnzjJG3oHFoI3IluBBGHHFZhhcLOdGma3c03Mfq0bzM0AVgPpQE+bnUdtxsDzswh6MBwzWSYNfEDwuKKaKEHlFPfv916QA6Mk+wdgavuewfZZ7T6fICA3snlP5m5RUoWIB2D2nmWCP2safWJsZ7Zzml3ztNf0yQFMvHz1lXDyClc87tkUfkW1WipRBQS8fm1uAwB0ojgGkLT+ZTHWzdAK+0kPGENFrtsNwt7Y9UcOpDa1k7KwY+j+ZKlBEzGiXPYQLIIp59I5dp2vDeJl3+ggX25tNY4rzGz6CEQeYmEgGBdABQUJ0HTNMarUx+5noyvunzrse3o1Jv8Jqkq80BaZ/g/BqNWoIa40UR9X6Mx0uWx8e/1vZIM8dUeTC0s1yYdKIT1jL+3WHWnA3FPZIW3akDlLVN8h1jVapwkTmbDO35d5T+lm/iJ3NaSDPQNBeWCcmcu3e/C68=
  app: ancient-cliffs-02532
